name: Test CICD

on:
  push:
    branches: [main]

jobs:
  test_cicd:
    runs-on: ubuntu-22.04

    steps:
      - name: Create a File
        run: |
          touch test
          echo "Hello World" > test


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: |
          aws s3 mv \
          test \
          ${{ secrets.S3_BUCKET }}/test