name: Test CICD

on:
  push:
    branches: [main]

jobs:
  test_cicd:
    runs-on: ubuntu-22.04

    steps:
      - name: Create a file
        run: |
	  touch .env
	  echo "Hello World" > .env
      - name: Read a File
	run: |
	  ls -al
	  cat .env
